Move --delete to a command line switch

diff --git a/sync-secure-s3 b/sync-secure-s3
--- a/sync-secure-s3
+++ b/sync-secure-s3
@@ -1,5 +1,19 @@
 #!/usr/bin/env bash
 
+fail() {
+  echo -e "$1\n"
+  exit 1
+}
+
+usage() {
+  echo "$(basename $0) [--delete]"
+  echo "Syncs directories to s3. Config file should be in ~/misc-utils-config.include"
+  echo "Append --delete to sync with the --delete flag set"
+}
+
+[ -n "$1" -a "--delete" != "$1" ] && fail "$(usage)"
+[ "$1" == "--delete" ] && DELETE_FLAG="--delete"
+
 BASH_DIR=$(dirname "$0")
 source ${BASH_DIR%*/}/common/common.include
 source ${HOME}/misc-utils-config.include
@@ -16,18 +30,5 @@ for index in ${!S3_SYNC_SECURE_SOURCE_PATH_DESTS[@]}; do
   echo "${source} -> ${dest}"
 
   # Sync all content into S3 that isn't there; don't delete anything in S3 even if not in the local copy
-  aws s3 sync --no-follow-symlinks --sse-c --sse-c-key "${KEY}" "${source}" "${dest}" || fail "error running aws s3 sync from ${source} -> ${dest}"
-
-  echo -e "\n\n------------- upload complete | showing dryrun with --delete\n"
-  # show what would happen with --delete, but don't do it (yet)
-  aws s3 sync --dryrun --delete --no-follow-symlinks --sse-c --sse-c-key "${KEY}" "${source}" "${dest}" || fail "error running aws s3 sync --delete dryrun from ${source} -> ${dest}"
-
-  echo -e "\nRun S3 sync with --delete [Yes | no] (case-sensitive)"
-  read yesno
-  if [ "${yesno}" != "Yes" ]; then
-    echo "Not deleting from S3"
-  else
-    echo "Deleting from S3"
-    aws s3 sync --delete --no-follow-symlinks --sse-c --sse-c-key "${KEY}" "${source}" "${dest}"  || fail "error running aws s3 sync --delete from ${source} -> ${dest}"
-  fi
+  aws s3 sync ${DELETE_FLAG} --no-follow-symlinks --exclude .DS_Store --sse-c --sse-c-key "${KEY}" "${source}" "${dest}" || fail "error running aws s3 sync from ${source} -> ${dest}"
 done
