sync-s3 support all CLI flags for aws s3 sync

diff --git a/sync-s3 b/sync-s3
--- a/sync-s3
+++ b/sync-s3
@@ -10,17 +10,14 @@ fail() {
 usage() {
   echo "$(basename $0) [--delete]"
   echo "Syncs directories to s3. Config file should be in ~/misc-utils-config.include"
-  echo "Append --delete to sync with the --delete flag set"
+  echo "Append s3 flags such as --delete to delete files not found locally, --dryrun for a dry run, and others"
 }
-
-[ -n "$1" -a "--delete" != "$1" ] && fail "$(usage)"
-[ "$1" == "--delete" ] && DELETE_FLAG="--delete"
-[ -n "${STORAGE_CLASS}" ] && STORAGE_CLASS_FLAG="--storage-class ${STORAGE_CLASS}"
 
 BASH_DIR=$(dirname "$0")
 source ${BASH_DIR%*/}/common/common.include
 source ${HOME}/misc-utils-config.include
 
+[ -n "${STORAGE_CLASS}" ] && STORAGE_CLASS_FLAG="--storage-class ${STORAGE_CLASS}"
 [ -n "${S3_SYNC_INSECURE_SOURCE_PATH_DESTS}" ] || fail "S3_SYNC_INSECURE_SOURCE_PATH_DESTS not set in config/common.include"
 
 echo "Syncing"
@@ -35,8 +32,8 @@ for index in ${!S3_SYNC_INSECURE_SOURCE_PATH_DESTS[@]}; do
     continue
   fi
 
-  # Sync all content into S3 that isn't there; don't delete anything in S3 even if not in the local copy
-  aws s3 sync ${DELETE_FLAG} ${STORAGE_CLASS_FLAG} --no-follow-symlinks --exclude ".DS_Store" "${source}" "${dest}" || fail "error running aws s3 sync from ${source} -> ${dest}"
+  # Sync all content into S3 that isn't there; pass through additional CLI args as flags on 'aws sync'
+  aws s3 sync ${@} ${STORAGE_CLASS_FLAG} --no-follow-symlinks --exclude ".DS_Store" "${source}" "${dest}" || fail "error running aws s3 sync from ${source} -> ${dest}"
 done
 
 echo "DONE"
